### ISSUE TITLE
Update typescript configuration

### ISSUE THREAD

**Issue by blazlew** [brains-and-beards/react-native-template-redbeard#14]
We can catch up tsconfig and package versions with this https://github.com/react-native-community/react-native-template-typescript

**Comment by PoorTable** [comment]
Update on TS template, repo in first comment is no longer actual one, I forgot that since 0.71 RN default template is TypeScript, but I found it and we should use https://github.com/facebook/react-native/tree/main/packages/react-native/template this one (<-) to check if we are up to date
