### ISSUE TITLE
Separate `prettier` from `eslint`

### ISSUE THREAD

**Issue by sharnik** [brains-and-beards/react-native-template-redbeard#25]
Currently we have two prettier configurations: one in `prettierrc` and another as an eslint rules inside `eslintrc`. This introduces multiple issues:
* For some rules (for example `trailingComma`) we have different settings between the two files. This makes it confusing when somebody wants to tweak the configuration. 
* Running `prettier` through `eslint` makes both run slower
* We're mixing responsibilities: linter should look for bugs and formatter should format code. Those are two separate tasks using two separate tools, so let's keep their configuration also separate

There's also an official stance from `prettier` maintainers on that practise:
* https://prettier.io/docs/en/comparison.html
* https://prettier.io/docs/en/integrating-with-linters.html

## Expected outcome
Separate eslint and prettier configurations - keep formatting defined in `prettier` and code checking in `eslint`.

**Comment by PoorTable** [comment]
I think closed?
